### ISSUE TITLE
Unable to use dollar-js in standalone node environment... depends on "window" for a lot of things

### ISSUE THREAD

**Issue by JessicaSachs** [seebigs/dollar-js#14]

**Comment by iwoodruff** [comment]
will this work?

https://github.com/seebigs/dollar-js/compare/woodruff/window_global?expand=1

**Comment by iwoodruff** [comment]
@seebigs any idea how to handle these guys?
```
if (elem === elem.window) { // handle window
```
in `core/_elementData.js`

**Comment by seebigs** [comment]
For the record, Jess was trying to do something like this in a Node app:
```
const $ = require('dollar-js');
const htmlString = '<html><body><ul class="myItem">Foo</ul><ul class="myItem">Bar</ul></body></html>';
const $htmlString = $(htmlString); // fails
// trying to get the inner text from the last UL element
```
This fails because dollar-js assumes that it runs in a browser-like environment with globals like
- window
- document
- Element
- Object
- Array
- etc.

**Comment by seebigs** [comment]
After some investigation, I don't think that it makes sense to add this feature to dollar-js. Our mission is focused on being a small tool for DOM interactions. Making the changes necessary to allow something like the above is just too far out of the dollar-js scope.

This need would be better met by what we're trying to build in the ParseTree project here: https://github.com/syntaxable/parsetree

There will eventually be an HTML code parser that wraps the nodes in a very similar dollar-js-like wrapper

**Comment by JessicaSachs** [comment]
kk! I ended up using Cheerio :-) https://github.com/cheeriojs/cheerio
